### ISSUE TITLE
External SSD btrfs volume not detected

### ISSUE THREAD

**Issue by initramfs** [maharmstone/btrfs#19]
An btrfs volume created with the command:

`mkfs -t btrfs /dev/sda1` (under a GPT filetable)

resulting in the following flags: `big_metadata`,  `extended_iref`,  `mixed_backref`,  `skinny_metadata` from Arch Linux 4.6.2 x64 with btrfs-progs v4.6 cannot be read (no drive is displayed in explorer or mountvol) from my Microsoft Windows 10 x64 partition.

The drive is being detected in disk manager but does not indicate a partition type. A seperate USB memory stick loaded with btrfs under the same system can be loaded and interacted with with no problem. The drive also used to work (i.e. it was working at one point with btrfs) until one day detection failed (as such, I tried reformatting it to no avail). The drive is detectable when formatted with exFAT or NTFS in Windows.

Upon insertion, I've tried restarting explorer, starting explorer from a priveleged command prompt, mounting all the drives available in mountvol, refreshing explorer with F5 and removal and reinserting the drive.

The Arch Linux and the Windows system reside on the same hardware (dual boot) and the same USB slot was used (though I've tried different slots as well to no avail). The drive functions as intended in Arch. The drive has also been tested in another Microsoft Windows 10 x64 system with the same results (no drive detection).

Attached below is the btrfs kernel log as well as the debugview log, note that in the kernel log all events up to the last 0000000000000CC0 occurred prior to any btrfs volume was inserted to the system.

[btrfs.txt](https://github.com/maharmstone/btrfs/files/332057/btrfs.txt)
[DebugView.txt](https://github.com/maharmstone/btrfs/files/332058/DebugView.txt)

I can provide more information as necessary.

**Comment by maharmstone** [comment]
Thank you, I'll look into it. It looks like we need to implement FSCTL_INVALIDATE_VOLUMES.

**Comment by maharmstone** [comment]
I've just released version 0.5, which contains an implementation of FSCTL_INVALDIATE_VOLUMES. Can you see if it fixes your problem, please?

**Comment by initramfs** [comment]
Unfortunately the drive is still not being detected. I've also additionally scrubbed the drive and checked it for errors (none reported by btrfs-progs). Attached are more btrfs logs though it seems like nothing has really changed since version 0.4 (except during unmount/eject). I've also tried keeping the device plugged in during booting (rather than hot plug it after loading into Windows which generated a much longer log, though still nothing appears in explorer or mountvol.

For simplicity, I've split the log into 3 files: __btrfs-boot__ for booting a system with no btrfs partitions attached; __btrfs-umount__ for the log that appears after the drive in question is unmounted (no log shows up when the drive is plugged in; __btrfs-mboot__ for when the drive was already plugged in on boot (this seems to generate a lot of log with no results). The DebugView log has also been attached.

[btrfs-boot.txt](https://github.com/maharmstone/btrfs/files/380654/btrfs-boot.txt)
[btrfs-mboot.txt](https://github.com/maharmstone/btrfs/files/380655/btrfs-mboot.txt)
[btrfs-umount.txt](https://github.com/maharmstone/btrfs/files/380657/btrfs-umount.txt)
[DebugView-v0.5.txt](https://github.com/maharmstone/btrfs/files/380656/DebugView-v0.5.txt)

**Comment by maharmstone** [comment]
I've just released a new version, which improves support for removable devices. Can you try with that please?

**Comment by initramfs** [comment]
Hi, sorry for the very late reply. Unfortunately the drive is still not being detected. I have since tried to use a different external enclosure with no results. The latest log is attached below:

[btrfs.txt](https://github.com/maharmstone/btrfs/files/473050/btrfs.txt)

**Comment by maharmstone** [comment]
Can you try on the version I've just released, please?

**Comment by initramfs** [comment]
Drive is still not detected in explorer. I noticed however that btrfs reports it's mounted (i.e. in registry I see the UUID listed). But explorer doesn't show it nor does any utility indicate it's presence. The closest I got was with the `dir` program, which gave me "The device is not ready." as opposed to a generic "The system cannot find the path specified." error. Using GPT fdisk I can read the GPT layout with the following information:

> Partition GUID code: 0FC63DAF-8483-4772-8E79-3D69D8477DE4 (Linux filesystem)
Partition unique GUID: 3D3CF52F-0CCA-4BA2-8CA1-DC6D89D8953E
First sector: 2048 (at 1024.0 KiB)
Last sector: 937701375 (at 447.1 GiB)
Partition size: 937699328 sectors (447.1 GiB)
Attribute flags: 0000000000000000
Partition name: ''

Indicating that the drive is readable at least to the partition table.

Prior to the version 0.7 I did try to switch the metadata profile to DUP from single to no effect.

Also, all of the above only applies when the drive is present on boot. If I hotplug the drive I get no reaction from anything (btrfs logs show nothing, registry doesn't indicate mount, dir claims no drive is mounted, etc).

The associated log from 0.7:
[btrfs-0.7.txt](https://github.com/maharmstone/btrfs/files/550479/btrfs-0.7.txt)

**Comment by maharmstone** [comment]
Hmm... there's no errors in that log - it looks like Windows is mounting the volume then ignoring it.

What does diskmgmt.msc look like? Are things any different if you use GPT fdisk to change the partition type to 0700?

**Comment by initramfs** [comment]
Sorry for the lack of response, I did not get time to test changing the partition type given I had data on the disk.

However, since version 0.9 detection now works as expected for the SSD, both hotplug and during boot, therefore I'll close the issue unless you require additional diagnostic data.
