### ISSUE TITLE
Can't copy from NTFS to BTRFS in Windows

### ISSUE THREAD

**Issue by kenny-w1** [maharmstone/btrfs#93]
Hello, I tried copying World of Warcraft 3.3.5a (16-17GB) from my NTFS windows drive to BTRFS(non-filesystem, backup storage harddrive), going from my primary harddrive (SSD) to my secondary harddrive (HDD), but it froze up & when I tried exiting it it ended up messing up my computer really bad making the explorer not respond, signing out & back in did not fix the problem but restarting did. 

I seem to be able to copy from BTRFS to NTFS on Windows, but not from NTFS to BTRFS on Windows.
Really like to see that someone is developing a BTRFS driver for Windows, makes things far more convenient, hope you guys can fix it up so copying stuff won't mess things up. Thank you.

If I have missed any relevant information please let me know & I will do what I can to provide you with what you need.

**Comment by maharmstone** [comment]
What you're describing is a deadlock, and sounds very much like a bug I quashed the other day. Can you please try the version I've just released, see if that improves things for you?

**Comment by gileshuang** [comment]
I just upgraded to 1.0.2, and this bug still hapend.
I copy a directory in NTFS which contain a game (30GB). While about 4.8GB copied, the Explorer frozen.
Source: NTFS on SSD.
Target: btrfs on HDD.

**Comment by gileshuang** [comment]
This is since the same issue with #58

**Comment by RobertBoganKang** [comment]
I cannot copy large files too. It stuck forever, and I force my system to restart by pressing power button.

**Comment by maharmstone** [comment]
I agree with both of Atemu12's comments in that thread - I'm very sceptical that something hasn't gone wrong there. Inline extents might account for it, but I very much doubt you have 40GB worth of tiny files there. Are you certain you don't have any sort of compression turned on?

If robocopy freezes on Btrfs but not NTFS, that's very much an issue with the driver...

**Comment by gileshuang** [comment]
1. I use Microsoft Explorer, not robocopy/rsync, and this bug happens.
2. I do not enable any compression on btrfs volume.
3. I copy a fold from NTFS to btrfs volume, which about 30GB with a game. I am very sure that btrfs frozen, not NTFS. While it frozen, I can not access the btrfs volume from Explorer, but can access NTFS volume.
4. I also mount this btrfs volume on Linux, without any compression. On Linux, this btrfs volume do not any issue.

**Comment by gileshuang** [comment]
By the way, I am using version 1.0.2, not the git version.
With Windows 10 1803(x64)

**Comment by maharmstone** [comment]
I've not been able to reproduce this, and I've copied gigabytes and gigabytes. Is your filesystem clean - what's the output of `btrfs check`?

**Comment by gileshuang** [comment]
I think the filesystem is clean.
There is the output of `btrfs check`
```
[root@Xeon-Linux ~] <2018-11-18 20:53:29>
# btrfs check /dev/sdc2
Opening filesystem to check...
Checking filesystem on /dev/sdc2
UUID: e09c0c2c-2586-4c6c-bff5-4a6bcd08e1b5
[1/7] checking root items
[2/7] checking extents
[3/7] checking free space cache
[4/7] checking fs roots
[5/7] checking only csums items (without verifying data)
[6/7] checking root refs
[7/7] checking quota groups skipped (not enabled on this FS)
found 37507375104 bytes used, no error found
total csum bytes: 36486568
total tree bytes: 134643712
total fs tree bytes: 90226688
total extent tree bytes: 3309568
btree space waste bytes: 20392402
file data blocks allocated: 37446782976
 referenced 37455122432
```

**Comment by maharmstone** [comment]
Thank you. I think I've sorted this now - it was actually a couple of different issues, all of which only manifested when copying large files at high speeds (> 100 MB/s).

https://github.com/maharmstone/btrfs/commit/2c0fcdb5f32b3c6c43664a276d27d33e1babf064
https://github.com/maharmstone/btrfs/commit/86ca3defe355863ee70a96de8cd170cbac784adf

**Comment by rox4d** [comment]
Strange, It is quite easy reproducible with disk in usb2 enclosure for me (Win7 x64), is there are plans to release a binary build with these fixes any time soon?

**Comment by gileshuang** [comment]
Since version 1.1 released, I tried copy two BIG folder from NTFS to BTRFS, using Windows Explorer.
One of the folder have 40GB data, contained both large files and small files.
One have 100GB data, with so many small files.
Both succeed, without any freeze.

I will keep using this driver. If there are some interesting new things, I will let you known.

**Comment by rox4d** [comment]
V1.1 seems to work here (win7-amd64), just copied about 100Gb  over  esata and about 40Gb over  usb2 without locks (v1.0.2 was locked almost immediately in both cases), it is great, thanks!

**Comment by maharmstone** [comment]
Excellent, thanks for letting me know!

**Comment by Zero3K** [comment]
I think this issue should be closed since it was fixed.

**Comment by maharmstone** [comment]
Closing old issues
